
- src: https://github.com/ait-cs-IaaS/acr-ansible-nginx-simple-webserver.git
  scm: git
  version: v1.0
  name: limesurvey-nginx-simple-webserver
 
- src: https://github.com/ait-cs-IaaS/acr-ansible-get-git-repo.git
  scm: git
  version: v1.0
  name: limesurvey-get-git-repo

- src: https://github.com/ait-cs-IaaS/acr-ansible-simple-systemd-service.git
  scm: git
  version: v1.0
  name: limesurvey-simple-systemd-service